config/routes.rb
Rails.application.routes.draw do
  resources :events do
    collection do
      get :report
    end
  end

  root 'events#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  validates :location, presence: true
  validates :total_amount, presence: true
  validates :paid_by_amar, presence: true
  validates :paid_by_akbar, presence: true
  validates :paid_by_anthony, presence: true

  enum event_types: [:lunch, :dinner, :snacks]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  def report
    
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:location, :total_amount, :paid_by_amar, :paid_by_akbar, :paid_by_anthony)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :event_type %><br>
    <%= f.select :event_type, Event.event_types %>
  </div>

  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :total_amount %><br>
    <%= f.text_field :total_amount %>
  </div>
  <div class="field">
    <%= f.label :paid_by_amar %><br>
    <%= f.text_field :paid_by_amar %>
  </div>

  <div class="field">
    <%= f.label :amar_present  %><br>
    <%= f.check_box :amar_present %>
  </div>

  <div class="field">
    <%= f.label :paid_by_akbar %><br>
    <%= f.text_field :paid_by_akbar %>
  </div>

  <div class="field">
    <%= f.label :akbar_present  %><br>
    <%= f.check_box :akbar_present %>
  </div>

  <div class="field">
    <%= f.label :paid_by_anthony %><br>
    <%= f.text_field :paid_by_anthony %>
  </div>

  <div class="field">
    <%= f.label :anthony_present  %><br>
    <%= f.check_box :anthony_present %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Events</h1>

<table>
  <thead>
    <tr>
      <th>Location</th>
      <th>Total amount</th>
      <th>Paid by amar</th>
      <th>Paid by akbar</th>
      <th>Paid by anthony</th>
      <th>amar was present</th>
      <th>akbar was present </th>
      <th>anthony was present </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.location %></td>
        <td><%= event.total_amount %></td>
        <td><%= event.paid_by_amar %></td>
        <td><%= event.paid_by_akbar %></td>
        <td><%= event.paid_by_anthony %></td>
        <td><%= event.amar_present %></td>
        <td><%= event.akbar_present %></td>
        <td><%= event.anthony_present %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>
<%= link_to 'Generate report ', report_events_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/report.html.erb
here gose  report !!!!

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Event Type:</strong>
  <%= @event.event_type %>
</p>

<p>
  <strong>Location:</strong>
  <%= @event.location %>
</p>

<p>
  <strong>Total amount:</strong>
  <%= @event.total_amount %>
</p>

<p>
  <strong>amar was there?:</strong>
  <%= @event.amar_present %>

  <strong>Paid by amar:</strong>
  <%= @event.paid_by_amar %>
</p>

<p>
  <strong>akbar was there?:</strong>
  <%= @event.paid_by_akbar %>

  <strong>Paid by akbar:</strong>
  <%= @event.akbar_present %>
</p>

<p>
  <strong>anthony was there?:</strong>
  <%= @event.anthony_present %>

  <strong>Paid by anthony:</strong>
  <%= @event.paid_by_anthony %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', report_events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CommonEat</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>